# Generated by Django 5.2.5 on 2025-09-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booknote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booknote',
            unique_together=set(),
        ),
    ]
